name: Request a Feature
description: Have an idea that would make GitHub Copilot for Azure better? Let us know!
type: "Feature"
labels:
  - ":bulb: feature request"
body:
  - type: dropdown
    id: topic
    attributes:
      label: What topic does your problem belong to?
      options:
        - Learn how to accomplish something in Azure
        - Query details of your resources
        - Troubleshoot an application hosted on Azure
        - Create and provision Azure resources
        - Learn about Azure costs
        - None of the above
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: Problem
      description: What are you trying to accomplish? What problems or difficulties are you experiencing?
      placeholder: |
        I'm unable to...
        I get confused when...
        I get frustrated when I try to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Desired Solution
      description: What solutions or fixes would you like to see?
      placeholder: |
        I'd like the extension to...
        It would be better if the extension can...
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: Alternatives and Workarounds
      description: Are there alternative solutions you have considered? How have you tried to work around this problem?
      placeholder: |
        Alternatively, it would be helpful if there was...
        To work around this problem, I've tried...
  
  - type: input
    id: impact
    attributes:
      label: Impact
      description: How often do you expect to use this feature? How much time will it save you? Is there any other impact you would like to share?

  - type: input
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots that can help us understand your feature request better.