trigger:
  branches:
    include:
    - main

pr: none

stages:
- stage: RunBenchmark
  displayName: 'Run Benchmarks'
  pool:
    name: $(LINUXPOOL)
    image: $(LINUXVMIMAGE)
    os: linux
  variables:
  - template: /pipelines/templates/variables/image.yml
  - template: /pipelines/templates/variables/globals.yml
  jobs:
  - job: RunBenchmark
    displayName: 'Run Copilot Benchmarks'
    steps:
    - template: /pipelines/templates/steps/install-uv.yml

    - pwsh: uv python install 3.12 && uv python pin 3.12
      displayName: 'Install Python 3.12 with uv'

    - task: PipAuthenticate@1
      displayName: 'Authenticate pip with MicrosoftSweBench feed'
      inputs:
        artifactFeeds: 'internal/MicrosoftSweBench'

    - task: AzureCLI@2
      displayName: 'Run Copilot Benchmarks script'
      inputs:
        connectedServiceNameARM: 'azure_msbench_eval'
        addSpnToEnvironment: true
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        scriptPath: $(Build.SourcesDirectory)/pipelines/scripts/Invoke-CopilotBenchmarks.ps1